---
- hosts: linux
  become: true

  tasks:
  
  - name: Update all installed packages in CentOS
    ansible.builtin.dnf:
      name: "*"
      state: latest
    notify: Reboot servers
    when: ansible_os_family == "RedHat"

  - name: Update all installed packages in Ubuntu
    ansible.builtin.apt:
      name: "*"
      state: latest  
      update_cache: true
    notify: Reboot servers
    when: ansible_os_family == "Debian"

  - name: Block login ssh root
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PermitRootLogin no'
      insertafter: "#PermitRootLogin"
      line: "PermitRootLogin no"
      state: present
      validate: '/usr/sbin/sshd -t -f %s'
    notify: Restart SSH Service
      

  handlers:  
  - name: Reboot servers
    ansible.builtin.reboot:
      
  - name: Restart SSH Service
    ansible.builtin.systemd_service:
#      name: ssh.service or sshd.service
      name: "{{ ('ssh' if ansible_os_family == 'Debian' else 'sshd') ~ '.service' }}"
      state: reloaded
   
